# Generated by Django 5.0.7 on 2024-07-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiyariHatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='題名')),
                ('process', models.CharField(max_length=100, verbose_name='工程')),
                ('action', models.CharField(max_length=100, verbose_name='やるべきこと')),
                ('situation', models.TextField(verbose_name='ヒヤリとした場面')),
                ('consequence', models.TextField(verbose_name='気づけなければ、どうなるのか')),
                ('avoidance', models.TextField(verbose_name='回避事由')),
                ('danger_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='危険度')),
                ('phase', models.CharField(choices=[('input', 'インプット情報'), ('reception', '受容'), ('judgment', '判断'), ('action', '行動')], max_length=20, verbose_name='様態評価')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
